cursor #e2e2e2
cursor_text_color #c6c6c6

foreground            #e2e2e2
background            #131313
selection_foreground  #1b3435
selection_background  #b0cccc
url_color             #4cdade

color0   #131313
color1   #ff4688
color2   #4cde58
color3   #fff146
color4   #2cced2
color5   #006366
color6   #4cdade
color7   #d6e8e9
color8   #828f90
color9   #ff81ae
color10  #89ff93
color11  #fff689
color12  #6bf0f4
color13  #89fbff
color14  #b3fcff
color15  #f6feff
