color0 #e2e2e2
color1 #ba1a1a
color2 #944171
color3 #725763
color4 #7f543b
color5 #a45c82
color6 #896a78
color7 #1b1b1b
color8 #777777
color9 #ba1a1a
color10 #944171
color11 #725763
color12 #7f543b
color13 #a45c82
color14 #896a78
color15 #1b1b1b

cursor                #1b1b1b
cursor_text_color     #f9f9f9
background            #f9f9f9
foreground            #1b1b1b
selection_foreground  #474747
selection_background  #e2e2e2
active_border_color   #944171
inactive_border_color #e2e2e2
url_color             #944171

active_tab_foreground   #ffffff
active_tab_background   #944171
inactive_tab_foreground #474747
inactive_tab_background #e2e2e2
cursor_trail_color      #474747
